#!/bin/sh
# usage: mpg2mp4.sh your_mpg your_avi
VBITRATE=500

mencoder "$1" -ovc frameno -o frameno.avi -oac mp3lame -lameopts vbr=3
mencoder "$1" -ovc lavc -lavcopts vcodec=mpeg4:vbitrate=$VBITRATE:vpass=1 -oac copy -o "$2"
mencoder "$1" -ovc lavc -lavcopts vcodec=mpeg4:vbitrate=$VBITRATE:vpass=2 -oac copy -o "$2"

rm -f frameno.avi
rm -f *.log
